version: '2'
services:
  ors-logs-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: ors-logs-elasticsearch
    environment:
      - cluster.name=ors-server-farm
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #mem_limit: 1g
    volumes:
      - /elasticsearch-data/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    container_name: ors-kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - ors-logs-es

networks:
  esnet: